apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: simplerollouttraits.extend.oam.dev
spec:
  revisionEnabled: true
  definitionRef:
    name: simplerollouttraits.extend.oam.dev
